/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_libmpt_library_WRAP_H_
#define SWIG_libmpt_library_WRAP_H_

struct SwigDirector_Mpt : public Mpt, public Swig::Director {

public:
    SwigDirector_Mpt(mpt_params params);
    virtual void OnNewTokenProcessed(std::string const &token);
    virtual void OnLogMessage(std::string const &information);
    virtual ~SwigDirector_Mpt();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(const char *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(const char *);
    void swig_connect_director(SWIG_Callback0_t callbackOnNewTokenProcessed, SWIG_Callback1_t callbackOnLogMessage);

private:
    SWIG_Callback0_t swig_callbackOnNewTokenProcessed;
    SWIG_Callback1_t swig_callbackOnLogMessage;
    void swig_init_callbacks();
};


#endif
